### ISSUE TITLE
[BUG] 깃헙 액션 에러

### ISSUE THREAD

**Issue by KingNono1030** [DevFDev/frontend#76]
## 🐞 버그 설명

- 발생한 버그에 대해 간단하게 설명해주세요.

## 📋 재현 방법

1. 어떤 상황에서 버그가 발생했는지 구체적인 재현 단계를 작성해주세요.
2. 예: '...'

## 🖼 예상 동작

- 예상했던 동작과 다른 동작이 있었다면 설명해주세요.

## 📸 스크린샷

- 필요하다면, 스크린샷이나 오류 메시지를 첨부해주세요.

![image](https://github.com/user-attachments/assets/9cb6fa64-6eb6-40d9-b317-7e2bb0d02ba9)
![image](https://github.com/user-attachments/assets/967f1dd5-682a-488f-b0ce-4aef326c520a)
```ubuntu
remote: Permission to KingNono1030/frontend_fork.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/KingNono1030/frontend_fork.git/': The requested URL returned error: 403
```
> 에러 메시지
> 403 코드, 포크리포지토리에 대한 접근 기각

---

![image](https://github.com/user-attachments/assets/31866a93-b965-43d7-834a-c93cd0f42015)
> fork 리포지토리의 권한 설정

---

![image](https://github.com/user-attachments/assets/7b46574c-1622-4ed2-a5db-8a6d37491f19)
> PAT 권한 설정

---

## 환경

- OS: [예: iOS]
- 브라우저 [예: Chrome, Safari]
- 버전 [예: 22]

---

2024.11.08

![image](https://github.com/user-attachments/assets/9e22d1ca-ba71-449f-a2dc-183bb744ea3b)
```
name: Git Push into Another Repo to Deploy to Vercel

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)
        run: sudo apt update && sudo apt install -y ruby && sudo gem install mustache

      - name: Creates output
        run: sh ./build.sh

      - name: Pushes to Another Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTH_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: KingNono1030
          destination-repository-name: frontend_fork
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.head_commit.message || 'Auto-deployed from GitHub Actions' }}
          target-branch: dev

      - name: Test Get Variable Exported by Push-to-Another-Repository
        run: echo $DESTINATION_CLONED_DIRECTORY
```

```
    permissions:
      contents: write
```

여태까지 쓰기 권한이 없어서 해결이 안되었던 거네요...
쓰기 권한을 바꾸고 workflow re-run 은 해보니 에러메시지가 권한에러에서 
```
error: Could not read 111972c1238f5d539efd01da537b9855ffb5b912
error: could not parse commit 111972c1238f5d539efd01da537b9855ffb5b912
```
커밋을 읽지 못하는 에러 라인으로 바뀌었고,
이는 fork 리포지토리에서 싱크를 맞춰주니까 해결이되었습니다..!
